# https://goreleaser.com
project_name: mediarr

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    main: .
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/l3uddz/mediarr/release.Version={{ .Version }}"
      - -X "github.com/l3uddz/mediarr/release.GitCommit={{ .ShortCommit }}"
      - -X "github.com/l3uddz/mediarr/release.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm64

# MacOS Universal Binaries
universal_binaries:
  -
    replace: true

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .Branch }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"