# https://goreleaser.com
project_name: mediarr

# Build
builds:
  -
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X "github.com/l3uddz/mediarr/build.Version={{ .Version }}"
      - -X "github.com/l3uddz/mediarr/build.GitCommit={{ .ShortCommit }}"
      - -X "github.com/l3uddz/mediarr/build.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: "tar.gz"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
