name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # dependencies
      - name: Install dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # lint
      - name: Run lint
        run: |
          make lint

      # test
      - name: Run tests
        run: |
          make test

      # build
      - name: Run build
        run: |
          make build
