name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # dependencies
      - name: dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.24.0

      # checkout
      - name: checkout
        uses: actions/checkout@v2

      # unshallow (for goreleaser)
      - name: unshallow
        run: git fetch --prune --unshallow

      # setup go
      - name: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1

      # lint
      - name: lint
        run: |
          make lint

      # test
      #- name: test
      #  run: |
      #    make test

      # cache
      - name: cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # vendor
      - name: vendor
        run: |
          make vendor

      # build
      - name: build
        run: |
          make snapshot

      # artifact
      - name: artifact
        uses: actions/upload-artifact@v1
        with:
          name: build_${GITHUB_SHA}
          path: dist/