name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # dependencies
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: goreleaser info
        run: goreleaser -v

      - name: task
        uses: arduino/setup-task@v1

      - name: task info
        run: task --version

      # checkout
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # setup go
      - name: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: go info
        run: |
          go version
          go env

      # cache
      - name: cache-paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: cache-build
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: cache-mod
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: cache-task
        uses: actions/cache@v2
        with:
          path: .task/**/*
          key: ${{ runner.os }}-go-task

      # vendor
      - name: vendor
        run: |
          task vendor

      # git status
      - name: git status
        run: git status

      # build
      - name: build
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          task snapshot

      # publish
      - name: publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          task publish

      # artifacts
      - name: artifact_linux
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_linux
          path: dist/*linux*

      - name: artifact_darwin
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_darwin
          path: dist/*darwin*

      - name: artifact_windows
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_windows
          path: dist/*windows*
