name: build
on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: checkout
        uses: actions/checkout@v2

      # unshallow (for goreleaser)
      - name: unshallow
        run: git fetch --prune --unshallow

      # setup go
      - name: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      # test
      #- name: test
      #  run: |
      #    make test

      # cache
      - name: cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # vendor
      - name: vendor
        run: |
          make vendor

      # build
      - name: build
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          make snapshot

      # get tag name
      - name: tag_name
        if: startsWith(github.ref, 'refs/tags/')
        uses: olegtarasov/get-tag@v2
        with:
          tagRegex: "v?(.+)"

      # publish
      - name: publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          make publish

      # artifacts
      - name: artifact_linux
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_linux
          path: dist/*linux*.tar.gz

      - name: artifact_darwin
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_darwin
          path: dist/*darwin*.tar.gz

      - name: artifact_windows
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_windows
          path: dist/*windows*.zip

      # docker build
      - name: docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cloudb0x/mediarr
          dockerfile: build/Dockerfile
          tag_with_ref: true
          tag_with_sha: true
          always_pull: true
